USE TEST1;
SELECT DB_NAME();

--DATE FUNCTION GETDATE()
SELECT GETDATE();

--DATEADD(interval, number, date)
SELECT DATEADD(MONTH,2,GETDATE());

--DATEDIFF(interval, start_date, end_date)
SELECT DATEDIFF(MONTH,2026-09-23,GETDATE());

--DATEPART(interval, date) / YEAR(date), MONTH(date), DAY(date)
SELECT MONTH(GETDATE());
SELECT DAY(GETDATE());
SELECT YEAR(GETDATE());
